In [2]:
import seaborn as sns 

tips = sns.load_dataset("tips")
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

## GroupBy
- 데이터셋.groupby(컬럼명).집계함수
    - 해당 컬럼명은 범주 형태 (즉, 숫자는 올 수 없음)
- 포인트 1. 데이터 형태가 바뀜
  - 추가적인 조작이 필요함

In [3]:
# 남자와 여자 누가 팁을 더 많이 줄까요? 

tips.groupby('sex', observed=True)['tip'].mean()

sex
Male      3.089618
Female    2.833448
Name: tip, dtype: float64

In [4]:
tips.groupby('sex', observed=True)['tip'].mean().reset_index()

      sex       tip
0    Male  3.089618
1  Female  2.833448

In [8]:
result = tips.groupby(['sex', 'day', 'smoker'], observed=True)['tip'].mean()
result.reset_index()

       sex   day smoker       tip
0     Male  Thur    Yes  3.058000
1     Male  Thur     No  2.941500
2     Male   Fri    Yes  2.741250
3     Male   Fri     No  2.500000
4     Male   Sat    Yes  2.879259
5     Male   Sat     No  3.256563
6     Male   Sun    Yes  3.521333
7     Male   Sun     No  3.115349
8   Female  Thur    Yes  2.990000
9   Female  Thur     No  2.459600
10  Female   Fri    Yes  2.682857
11  Female   Fri     No  3.125000
12  Female   Sat    Yes  2.868667
13  Female   Sat     No  2.724615
14  Female   Sun    Yes  3.500000
15  Female   Sun     No  3.329286

In [9]:
tips.groupby('sex', observed=True)['tip'].agg(['mean', 'std', 'max', 'min'])

            mean       std   max  min
sex
Male    3.089618  1.489102  10.0  1.0
Female  2.833448  1.159495   6.5  1.0

In [10]:
tips.groupby('sex', observed=True)['tip'].agg(['mean', 'std', 'max', 'min']).reset_index()

      sex      mean       std   max  min
0    Male  3.089618  1.489102  10.0  1.0
1  Female  2.833448  1.159495   6.5  1.0

In [11]:
tips.groupby('sex', observed=True)['tip'].size().reset_index() #각 행의 개수

      sex  tip
0    Male  157
1  Female   87

## 문제
- total_bill이 20보다 큰 행들만 필터링하세요.

In [ ]:
# 코드

- total_bill이 20보다 크고 tip이 3보다 큰 행들만 필터링하세요.

In [ ]:
# 코드

## 문제 
- Sun, Sat만 출력

In [3]:
tips['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [ ]:
# code

## 문제
- New가 들어간 도시만 출력
- contains 메서드 활용

In [8]:
import pandas as pd

data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'city': ['New York', 'Los Angeles', 'New Yorker', 'Chicago', 'New City'],
    'age': [25, 30, 35, 40, 45]
}

df = pd.DataFrame(data)
df

      name         city  age
0    Alice     New York   25
1      Bob  Los Angeles   30
2  Charlie   New Yorker   35
3    David      Chicago   40
4      Eva     New City   45

In [ ]:
# code